"""empty message

Revision ID: 533a73ccfac1
Revises: 810cea45c2ea
Create Date: 2020-09-30 20:08:06.697410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '533a73ccfac1'
down_revision = '810cea45c2ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch',
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('batch_id', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('aggregated_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('lines', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('sport', sa.String(), nullable=True),
    sa.Column('lines', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lines')
    op.drop_table('aggregated_lines')
    op.drop_table('batch')
    # ### end Alembic commands ###
