"""empty message

Revision ID: 810cea45c2ea
Revises: 
Create Date: 2020-09-18 15:07:40.154366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '810cea45c2ea'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('results',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lines', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('results')
    # ### end Alembic commands ###
