"""empty message

Revision ID: 8665d1acba77
Revises: 
Create Date: 2020-10-19 14:18:36.653357

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8665d1acba77'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.String(), nullable=True),
    sa.Column('created_time', sa.DateTime(), nullable=True),
    sa.Column('book', sa.String(), nullable=True),
    sa.Column('lines', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.batch_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('book_history')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('book', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lines', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.batch_id'], name='book_history_batch_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='book_history_pkey')
    )
    op.drop_table('book_records')
    # ### end Alembic commands ###
